-- +goose Up
-- +goose StatementBegin
CREATE TABLE tokens
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT unique                           NOT NULL,
    access             VARCHAR unique                          NOT NULL,
    refresh            VARCHAR unique                          NOT NULL,
    expires_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    refresh_expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

ALTER TABLE tokens
    ADD CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE tokens;
-- +goose StatementEnd
